channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - bokeh
  - cartopy
  - dask
  - numpy
  - netCDF4
  - matplotlib
  - pillow
  - gdal
  - pandas
  - geopandas
  - pytz
  - scikit-image
  - scikit-learn
  - shapely
  - scipy
  - astropy
  - spyder
  - notebook
  - xarray
  - requests
